const fakeUsers=[
  [
    {
      "id": 6,
      "username": "string23",
      "firstname": "string",
      "surname": "string",
      "email": "string",
      "birthday": "2022-08-16 22:52:04.873000 +00:00",
      "created_at": "2022-08-16 23:07:12.600638 +00:00",
      "follower_count": 0,
      "following_count": 0,
      "post_count": 0,
      "comment_count": 0,
      "is_actived": false,
      "is_blocked": false,
      "password_salt": "string",
      "password_hass": "string",
      "avatar": null
    },
    {
      "id": 7,
      "username": "string34",
      "firstname": "string",
      "surname": "string",
      "email": "string",
      "birthday": "2022-08-16 22:52:04.873000 +00:00",
      "created_at": "2022-08-16 23:08:33.566637 +00:00",
      "follower_count": 0,
      "following_count": 0,
      "post_count": 0,
      "comment_count": 0,
      "is_actived": false,
      "is_blocked": false,
      "password_salt": "string",
      "password_hass": "string",
      "avatar": null
    },
    {
      "id": 8,
      "username": "strin44g",
      "firstname": "string",
      "surname": "string",
      "email": "string",
      "birthday": "2022-08-16 22:52:04.873000 +00:00",
      "created_at": "2022-08-16 23:12:08.586065 +00:00",
      "follower_count": 0,
      "following_count": 0,
      "post_count": 0,
      "comment_count": 0,
      "is_actived": false,
      "is_blocked": false,
      "password_salt": "string",
      "password_hass": "string",
      "avatar": null
    },
    {
      "id": 3,
      "username": "strin1g3",
      "firstname": "stri3ng",
      "surname": "st2ring",
      "email": "strin21g4",
      "birthday": "2022-08-16 22:52:04.873000 +00:00",
      "created_at": null,
      "follower_count": null,
      "following_count": null,
      "post_count": null,
      "comment_count": null,
      "is_actived": false,
      "is_blocked": false,
      "password_salt": "string",
      "password_hass": "string",
      "avatar": null
    },
    {
      "id": 9,
      "username": "1string",
      "firstname": "1string",
      "surname": "1string",
      "email": "1string",
      "birthday": "2022-08-16 23:54:44.872000 +00:00",
      "created_at": "2022-08-16 23:56:26.429935 +00:00",
      "follower_count": 0,
      "following_count": 0,
      "post_count": 0,
      "comment_count": 0,
      "is_actived": false,
      "is_blocked": false,
      "password_salt": "1string",
      "password_hass": "1string",
      "avatar": null
    },
    {
      "id": 2,
      "username": "ikinic",
      "firstname": "ikinic",
      "surname": "string",
      "email": "string",
      "birthday": "2022-08-17 00:01:59.316000 +00:00",
      "created_at": null,
      "follower_count": null,
      "following_count": null,
      "post_count": null,
      "comment_count": null,
      "is_actived": false,
      "is_blocked": false,
      "password_salt": "string",
      "password_hass": "string",
      "avatar": null
    }
  ]
]

export {fakeUsers}
